/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tictactoe;

import java.awt.Event;
import java.awt.geom.Rectangle2D;

import com.sun.glass.events.MouseEvent;

import javafx.application.Application;
import javafx.event.EventType;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.scene.Node;
import javafx.scene.shape.Rectangle;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.control.TextArea;
public class App extends Application{

  @Override
  public void start(Stage stage) throws Exception{
    VBox vBox = new VBox();
    Scene scene = new Scene(vBox);

    Canvas canvas = new Canvas();
    canvas.setHeight(512);
    canvas.setWidth(1024);
    vBox.getChildren().add(canvas);

    Text text = new Text();
    vBox.getChildren().add(text);

    GraphicsContext gc = canvas.getGraphicsContext2D();
    gc.setFill(Color.DARKMAGENTA);

    GameBoardAdvanced gba = new GameBoardAdvanced(10, 0, 500, 500);
    gba.thicknessOfInsideBorders = 2;
    GameBoardAdvanced.paint(gc, gba);
    

    canvas.setOnMouseReleased(event -> {
      text.setText("x is: " + event.getX() + " y is: " + event.getY());
      gba.pointClicked((int) event.getX(),(int) event.getY());
      gc.setFill(Color.WHITE);
      gc.fillRect(0, 0, 512, 1024);
      gc.setFill(Color.MAGENTA);
      GameBoardAdvanced.paint(gc, gba);
    });

    stage.setScene(scene);
    stage.show();
  }

  public static void main(String[] args){
    launch(args);
  }
}
